/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.airwallex.issuing.gpt

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    if (2 == 3) {
        if (4 == 5) {
            val i = 10
            println(i)
        }
    }
    while (true) {
        while (true) {
            println(test)
        }
    }
}
