/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.airwallex.issuing.gpt

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    if (2 == 3) {
        if (4 == 5) {
            val i = 10
            println(i)
        }
    }
    while (true) {
        while (true) {
            println("test")
        }
    }

    val r = 40/0
    println(r)

    val GITHUB_API_KEY = "adkjhfdiuhAUUDUIDH298y32387232"
    println(GITHUB_API_KEY)

    val CREDIT_CARD = "4444333322221111"
    println(CREDIT_CARD)
}

fun notUsedMethod() {
    println("I dont do anything")
}