/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.airwallex.issuing.gpt

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {

    }

    fun notUsedMethod() {
        println("I dont do anything")
    }

    fun check() {
        if (2 == 3) {
            if (4 == 5) {
                val i = 10
                println(i)
            }
        }
        while (true) {
            while (true) {
                println("test")
            }
        }

        val r = 40/0
        println(r)

        val GITHUB_API_KEY = "adkjhfdiuhAUUDUIDH298y32387232"
        println(GITHUB_API_KEY)

        val CREDIT_CARD = "4444333322221111"
        println(CREDIT_CARD)
    }
}
